from __future__ import annotations

from typing import Final

PAYMENT_MODE_MANUAL: Final = "manual"
PAYMENT_MODE_TELEGRAM_STARS: Final = "telegram_stars"
PAYMENT_MODE_YOOKASSA_SBP: Final = "yookassa_sbp"
PAYMENT_MODE_TELEGRAM_PAYMENTS_LEGACY: Final = "telegram_payments"

SUPPORTED_PAYMENT_MODES: Final = frozenset(
    {
        PAYMENT_MODE_MANUAL,
        PAYMENT_MODE_TELEGRAM_STARS,
    }
)

TELEGRAM_STARS_CURRENCY: Final = "XTR"
TELEGRAM_STARS_PROVIDER_TOKEN: Final = ""
RUSSIAN_RUBLE_CURRENCY: Final = "RUB"

ORDER_STATUS_PENDING: Final = "pending"
ORDER_STATUS_PAYMENT_RECEIVED: Final = "payment_received"
ORDER_STATUS_ACTIVATING: Final = "activating"
ORDER_STATUS_PAID: Final = "paid"
ORDER_STATUS_ACTIVATION_FAILED: Final = "activation_failed"
ORDER_STATUS_FAILED: Final = "failed"
ORDER_STATUS_REFUNDING: Final = "refunding"
ORDER_STATUS_REFUNDED: Final = "refunded"
ORDER_STATUS_CANCELLED: Final = "cancelled"
ORDER_STATUS_EXPIRED: Final = "expired"

ORDER_KIND_PURCHASE: Final = "purchase"
ORDER_KIND_EXTEND: Final = "extend"
ORDER_KIND_EXTEND_AND_UPGRADE: Final = "extend_and_upgrade"
ORDER_KIND_RENEWAL: Final = ORDER_KIND_EXTEND
ORDER_KIND_RESUME: Final = "resume"
ORDER_KIND_UPGRADE_DEVICES: Final = "upgrade_devices"

ORDER_KINDS_WITH_PAID_DURATION: Final = frozenset(
    {
        ORDER_KIND_PURCHASE,
        ORDER_KIND_EXTEND,
        ORDER_KIND_EXTEND_AND_UPGRADE,
        ORDER_KIND_RESUME,
    }
)

COMMERCIAL_ENTITLEMENT_SOURCE_PAID_ORDER: Final = "paid_order"
COMMERCIAL_ENTITLEMENT_SOURCE_COMPLIMENTARY_ORDER: Final = "complimentary_order"
DEVICE_UPGRADE_PRICED_ENTITLEMENT_SOURCES: Final = frozenset(
    {
        COMMERCIAL_ENTITLEMENT_SOURCE_PAID_ORDER,
        COMMERCIAL_ENTITLEMENT_SOURCE_COMPLIMENTARY_ORDER,
    }
)

SUBSCRIPTION_STATUS_ACTIVE: Final = "active"
SUBSCRIPTION_STATUS_DISABLED: Final = "disabled"
SUBSCRIPTION_STATUS_EXPIRED: Final = "expired"

ENTITLEMENT_STATUS_ACTIVE: Final = "active"
ENTITLEMENT_STATUS_DISABLED: Final = "disabled"
ENTITLEMENT_STATUS_EXPIRED: Final = "expired"

TRIAL_STATUS_ACTIVATING: Final = "activating"
TRIAL_STATUS_ACTIVE: Final = "active"
TRIAL_STATUS_CONVERTED: Final = "converted"
TRIAL_STATUS_EXPIRED: Final = "expired"
TRIAL_STATUS_REVOKED: Final = "revoked"
TRIAL_STATUS_ACTIVATION_FAILED: Final = "activation_failed"

TRIAL_DURATION_HOURS: Final = 48
TRIAL_DURATION_SECONDS: Final = TRIAL_DURATION_HOURS * 60 * 60
TRIAL_MAX_DEVICES: Final = 1

REFERRAL_REWARD_PERCENT: Final = 20

SUPPORT_STATUS_WAITING_USER: Final = "waiting_user"
SUPPORT_STATUS_WAITING_SUPPORT: Final = "waiting_support"
SUPPORT_STATUS_WAITING_USER_REPLY: Final = "waiting_user_reply"
SUPPORT_STATUS_CLOSED: Final = "closed"

ORDER_ACTIVATION_RETRY_STATUSES: Final = frozenset(
    {
        ORDER_STATUS_PAYMENT_RECEIVED,
        ORDER_STATUS_ACTIVATION_FAILED,
        ORDER_STATUS_ACTIVATING,
    }
)

ORDER_ACTIVATION_ALLOWED_STATUSES: Final = frozenset(
    {
        ORDER_STATUS_PAYMENT_RECEIVED,
        ORDER_STATUS_ACTIVATING,
        ORDER_STATUS_ACTIVATION_FAILED,
    }
)

ORDER_REFUNDABLE_STATUSES: Final = frozenset(
    {
        ORDER_STATUS_PAYMENT_RECEIVED,
        ORDER_STATUS_ACTIVATING,
        ORDER_STATUS_ACTIVATION_FAILED,
        ORDER_STATUS_PAID,
    }
)

PAYMENT_INBOX_RECEIVED: Final = "received"
PAYMENT_INBOX_MATCHED: Final = "matched"
PAYMENT_INBOX_APPLIED: Final = "applied"
PAYMENT_INBOX_MANUAL_REVIEW: Final = "manual_review"
PAYMENT_INBOX_REFUND_REQUIRED: Final = "refund_required"
PAYMENT_INBOX_REFUNDED: Final = "refunded"

ENTITLEMENT_OPERATION_PENDING: Final = "pending"
ENTITLEMENT_OPERATION_CLAIMED: Final = "claimed"
ENTITLEMENT_OPERATION_EXTERNAL_UNKNOWN: Final = "external_unknown"
ENTITLEMENT_OPERATION_EXTERNAL_APPLIED: Final = "external_applied"
ENTITLEMENT_OPERATION_LOCAL_COMMIT_PENDING: Final = "local_commit_pending"
ENTITLEMENT_OPERATION_COMPLETED: Final = "completed"
ENTITLEMENT_OPERATION_FAILED_RETRIABLE: Final = "failed_retriable"
ENTITLEMENT_OPERATION_FAILED_TERMINAL: Final = "failed_terminal"
ENTITLEMENT_OPERATION_SUPERSEDED: Final = "superseded"
ENTITLEMENT_OPERATION_MANUAL_REVIEW: Final = "manual_review"
ENTITLEMENT_OPERATION_COMPENSATING: Final = "compensating"
ENTITLEMENT_OPERATION_COMPENSATED: Final = "compensated"

ENTITLEMENT_OPERATION_ACTIVE_STATES: Final = frozenset(
    {
        ENTITLEMENT_OPERATION_PENDING,
        ENTITLEMENT_OPERATION_CLAIMED,
        ENTITLEMENT_OPERATION_EXTERNAL_UNKNOWN,
        ENTITLEMENT_OPERATION_EXTERNAL_APPLIED,
        ENTITLEMENT_OPERATION_LOCAL_COMMIT_PENDING,
        ENTITLEMENT_OPERATION_FAILED_RETRIABLE,
        ENTITLEMENT_OPERATION_COMPENSATING,
    }
)

REFUND_OPERATION_PREPARED: Final = "prepared"
REFUND_OPERATION_PROVIDER_UNKNOWN: Final = "provider_unknown"
REFUND_OPERATION_PROVIDER_REFUNDED: Final = "provider_refunded"
REFUND_OPERATION_COMPENSATION_PENDING: Final = "compensation_pending"
REFUND_OPERATION_COMPENSATING: Final = "compensating"
REFUND_OPERATION_COMPLETED: Final = "completed"
REFUND_OPERATION_MANUAL_REVIEW: Final = "manual_review"

TELEGRAM_STARS_PROVIDERS: Final = frozenset(
    {
        PAYMENT_MODE_TELEGRAM_STARS,
        PAYMENT_MODE_TELEGRAM_PAYMENTS_LEGACY,
    }
)
